namespace AlliED.Views;

internal static class CondToolWindowResources
{
    public static readonly string AddToClipBtnGlyph = @"
52000000424D52000000000000003E0000002800000005000000050000000100
010000000000140000000000000000000000020000000000000000000000FFFF
FF00D8000000D800000000000000D8000000D8000000
";

    public static readonly string[] PercentBoxStrings = new string[]
    {
        "100%",
        "75%",
        "50%",
        "25%",
        "At least one",
        "All but one",
        "The special craft",
        "All non-special craft",
        "All non-player craft",
        "All player craft",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "66%",
        "33%",
        "Each craft",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
    };

    public static readonly string[] ClassBoxStrings = new string[]
    {
        "None ?",
        "Flight Group",
        "Ship Type",
        "Ship Category",
        "Object Category",
        "IFF",
        "Craft with orders",
        "Craft when",
        "Global Group (GG)",
        "9",
        "10",
        "11",
        "Team",
        "Player of GG",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "any Team except",
        "22",
        "Global Unit (GU)",
        "24",
        "25",
        "26",
        "Message #",
        "28",
        "29",
        "30",
        "31",
    };

    public static readonly string[] CondBoxStrings = new string[]
    {
        "(Always true)",
        "arrive",
        "be destroyed",
        "be attacked",
        "be captured",
        "be inspected",
        "be boarded",
        "finish docking",
        "be disabled",
        "exist (survive)",
        "(Never true)",
        "11",
        "complete mission",
        "complete primary goal",
        "fail primary goal",
        "complete secondary goal",
        "fail secondary goal",
        "complete bonus goal",
        "fail bonus goal",
        "be dropped off",
        "be reinforced",
        "have 0% shields",
        "be at 50% hull",
        "run out of missiles",
        "(arrive?)",
        "be dropped off",
        "be unharmed?",
        "NOT be disabled",
        "NOT be bagged",
        "destroyed without inspection",
        "be docked with",
        "NOT be docked with",
        "begin boarding",
        "NOT begin boarding",
        "be at 50% shields",
        "be at 25% shields",
        "be at 75% hull",
        "be at 25% hull",
        "38",
        "39",
        "40",
        "be all Player craft",
        "reinforced by A.I.?",
        "come and go",
        "be bagged",
        "withdraw",
        "be carried away",
        "arrive in Region #",
        "leave Region #",
        "be in proximity of",
        "be outside proximity of",
        "51",
        "defect",
        "be towing it",
        "be delivered?",
        "55",
        "be shown",
        "be I.D.ed",
        "(be I.D.ed)",
        "59",
        "60",
        "61",
        "62",
        "63",
        "64",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
    };
}
