namespace AlliED.Views;

internal static class DatapadWindowResources
{
    public static readonly string AddOrderBtnGlyph = @"
52000000424D52000000000000003E0000002800000005000000050000000100
010000000000140000000000000000000000020000000000000000000000FFFF
FF00D8000000D800000000000000D8000000D8000000
";

    public static readonly string ExtBtnGlyph = @"
82000000424D8200000000000000760000002800000005000000030000000100
0400000000000C00000000000000000000001000000000000000000000000000
80000080000000808000800000008000800080800000C0C0C000808080000000
FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFFFF00770770007000
700000000000
";

    public static readonly string[] PlayerBoxStrings = new string[]
    {
            "(A.I.)",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
    };

    public static readonly string[] TeamBoxStrings = new string[]
    {
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
    };

    public static readonly string[] ShipBoxStrings = new string[]
    {
            "(None)",
            "Xwing",
            "Ywing",
            "Awing",
            "Bwing",
            "TIE Fighter",
            "TIE Interceptor",
            "TIE Bomber",
            "TIE Advanced",
            "TIE Defender ",
            "Authority IRD",
            "Toscan Fighter",
            "Missile Boat",
            "Twing",
            "Z-95",
            "R-41",
            "Gunboat",
            "Shuttle",
            "Escort Shuttle",
            "System Patrol Craft",
            "Scout Craft",
            "Stormtrooper Transpost",
            "Assault Transport",
            "Escort Transport",
            "Tug",
            "Combat Utility Vehicle",
            "CN/A Brick",
            "CN/B Hexbox",
            "CN/C Tube",
            "CN/D Pronged",
            "Heavy Lifter",
            "Mole Miner",
            "Bulk Freighter",
            "Cargo Ferry",
            "Modular Conveyor",
            "Container Transpost",
            "Rebel Med Transport",
            "Muurian Transport",
            "Corellian Transport",
            "Millenium Falcon",
            "Corellian Corvette",
            "Modified Corvette",
            "Nebulon B Frigate",
            "Modified Neb B Frigate",
            "Passenger Liner",
            "Carrack Cruiser",
            "Strike Cruiser",
            "Escort Carrier",
            "Dreadnaught",
            "Calamari Cruiser",
            "Lt Calamari Cruiser",
            "Interdictor",
            "Victory Star Destroyer",
            "Imperial Star Destroyer",
            "Super Star Destroyer",
            "CN/E Hemisphere",
            "CN/F Slotted",
            "CN/G Hourglass",
            "CN/H Gem",
            "CN/I Y shaped",
            "Platform 1",
            "Platform 2",
            "Platform 3",
            "Platform 4",
            "Platform 5",
            "Platform 6",
            "Asteroid Hangar",
            "Asteroid Laser Battery",
            "Asteroid Warhd Launcher",
            "Factory",
            "Satellite1",
            "Satellite2",
            "Satellite3",
            "*Satellite4",
            "*Satellite5",
            "Mine1",
            "Mine2",
            "Mine3",
            "Gun Platform",
            "*Mine5",
            "Probe1",
            "Probe Capsule",
            "*Probe3",
            "Buoy1",
            "Buoy2",
            "Hyper buoy",
            "Asteroid",
            "Planet",
            "Rendezvous Buoy",
            "Cargo Canister",
            "Shipyard",
            "Repair Yard",
            "*Mod Strike Cruiser",
            "Lancer Frigate",
            "Bulk Cruiser",
            "Assault Frigate",
            "Corellian Gunship",
            "Imperial Landing Craft",
            "Assault Shuttle",
            "Marauder Corvette",
            "Star Galleon",
            "Imp Research Ship",
            "Luxury Yacht 3000",
            "Ferryboat Liner ",
            "Modified Action Transpost",
            "Mobquet Transport",
            "Xiytiar Transport",
            "Freight Transport/C",
            "Freight Transport/H",
            "Freight Transport/K",
            "YT-2000",
            "YT-2400",
            "Suprosa",
            "Skipray Blastboat",
            "TIE Experimental M1",
            "TIE Experimental M2",
            "TIE Experimental M3",
            "TIE Experimental M4",
            "TIE Experimental M5",
            "Cloakshape Fighter",
            "Razor Fighter",
            "Planetary Fighter",
            "Supa Fighter",
            "Pinook Fighter",
            "*Booster Pack",
            "Preybird Fighter",
            "*StarViper",
            "Firespray",
            "Pursuer",
            "Golan One Station",
            "Golan Two Station",
            "Golan Three Station",
            "Derilyn Platform",
            "Sensor Array",
            "Comm Relay",
            "Space Colony 1",
            "Space Colony 2",
            "Space Colony 3",
            "Casino",
            "Cargo Facility 1",
            "Cargo Facility 2",
            "Asteroid Mining Unit",
            "Processing Plant",
            "Rebel Platform",
            "Imperial Research Center",
            "Family Base",
            "Family Repair Yard",
            "Pirate Ship Yard",
            "Industrial Complex",
            "*Pirate Junkyard Base",
            "Escape Pod Type 1",
            "Pressure Tank",
            "CN/J Grande",
            "CN/K Box",
            "CN/L Sphere",
            "CN/Hangar",
            "Lrg Gun Emplace",
            "Lrg Gun/Wrhd Empl",
            "Proximity Mine A",
            "Proximity Mine B",
            "*Homing Mine A",
            "Homing Mine B",
            "New Laser battery",
            "New Ion battery",
            "Cargo Freighter",
            "*Cargo Freighter 2",
            "*Cargo Freighter 3",
            "*Cargo Freighter 4",
            "*Cargo Freighter 5",
            "Cargo Tanker",
            "*Cargo Tanker 2",
            "*Cargo Tanker 3",
            "*Cargo Tanker 4",
            "*Cargo Tanker 5",
            "Escape Pod Type 2",
            "*Rebel Pilot",
            "*Imp Pilot",
            "*Civ Pilot",
            "ZeroG Stormtrooper",
            "ZeroG Utility",
            "Emkay",
            "Astromech Droid",
            "Worker Droid",
            "Backdrop / Light (RGB->)",
            "184",
            "185",
            "186",
            "187",
            "188",
            "189",
            "190",
            "191",
            "192",
            "193",
            "194",
            "195",
            "196",
            "197",
            "198",
            "199",
            "200",
            "201",
            "202",
            "203",
            "204",
            "205",
            "206",
            "207",
            "208",
            "209",
            "210",
            "211",
            "212",
            "213",
            "214",
            "215",
            "216",
            "217",
            "218",
            "219",
            "220",
            "221",
            "222",
            "223",
            "224",
            "225",
            "226",
            "Death Star II",
            "Winged Calamari Cruiser",
            "VSD II",
            "ISD II",
            "231",
    };

    public static readonly string[] ShipNameStrings = new string[]
    {
            "1.0 1.0 1.0",
            "Red",
            "Blue",
            "Green",
            "Gold",
            "Rogue",
            "Avenger",
            "Alpha",
            "Beta",
            "Gamma",
            "Delta",
            "Eta",
            "Eagle",
            "Mu",
            "Nu",
            "Rho",
            "Tau",
            "Theta",
            "Zeta",
            "Liberty",
            "Defiance",
            "Iota",
            "Omicron",
            "Lambda",
            "Omega",
            "Kappa",
            "Sigma",
            "Upsilon",
            "Chi",
            "Pi",
            "Xi",
    };

    public static readonly string[] PlrPosSpinStrings = new string[]
    {
            "2 (1)",
            "2",
            "3",
            "4",
            "5",
            "6",
    };

    public static readonly string[] OpShipTypesStrings = new string[]
    {
            "No other craft",
            "All Friendly Flyable Craft",
            "All Rebel Starfighters",
            "All Flyble Freighters",
            "User Defined Options",
    };

    public static readonly string[] RoleBoxStrings = new string[]
    {
            "Command Ship",
            "Base",
            "Station",
            "Mission Critical Craft",
            "Convoy Craft",
            "Strike Craft",
            "Reload Craft",
            "Primary Target",
            "Secondary Target",
            "Tertiary Target",
            "Resource Centre",
            "Facility",
            "HYP from Region 1",
            "HYP from Region 2",
            "HYP from Region 3",
            "HYP from Region 4",
            "HYP to Region 1",
            "HYP to Region 2",
            "HYP to Region 3",
            "HYP to Region 4",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
    };

    public static readonly string[] Role2BoxStrings = new string[]
    {
            "Command Ship",
            "Base",
            "Station",
            "Mission Critical Craft",
            "Convoy Craft",
            "Strike Craft",
            "Reload Craft",
            "Primary Target",
            "Secondary Target",
            "Tertiary Target",
            "Resource Centre",
            "Facility",
            "HYP from Region 1",
            "HYP from Region 2",
            "HYP from Region 3",
            "HYP from Region 4",
            "HYP to Region 1",
            "HYP to Region 2",
            "HYP to Region 3",
            "HYP to Region 4",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
    };

    public static readonly string[] OrderDescEdStrings = new string[]
    {
            "Aeron",
            "Emon",
            "Emkay",
            "RP1",
            "RP2",
            "RP3",
            "RP4",
            "RP5",
            "RP6",
            "RP7",
            "RP8",
            "RP9",
            "RP10",
            "RP11",
            "RP12",
    };

    public static readonly string[] DifficultyBoxStrings = new string[]
    {
            "All levels",
            "Easy",
            "Medium",
            "Hard",
            ">Easy",
            "<Hard",
            "Never",
    };

    public static readonly string[] DepartWhenBoxStrings = new string[]
    {
            "never",
            "shields out",
            "2",
            "out of missles",
            "at 50% hull",
            "attacked",
            "at 50% shields",
            "at 25% shields",
            "at 75% hull",
            "at 25% hull",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
    };

    public static readonly string[] OrderBoxStrings = new string[]
    {
            "Hold Steady",
            "Fly home",
            "Circle waypoints",
            "Circle and Evade",
            "Rendezvous",
            "Disabled",
            "Await boarding",
            "Attack targets",
            "Attack escorts of",
            "Protect",
            "Escort (prevent boarding)",
            "Disable targets",
            "Board to Give/Reload",
            "Board to Take",
            "Board to Exchange",
            "Board to Capture",
            "Board to Destroy",
            "Pick up/Bag",
            "Drop off/Deploy",
            "Wait 1",
            "Wait 2",
            "SShip Circle",
            "SShip await return",
            "SShip await launch",
            "SS Patrol + protect",
            "SS Patrol + protect 2",
            "SS Patrol + attack",
            "SS Patrol + disable",
            "SShip Hold Steady 1",
            "SShip Fly Home",
            "SShip Hold Steady 2",
            "Board to ?",
            "Board to repair",
            "SShip hold Steady 3",
            "SShip hold Steady 4",
            "SShip hold Steady 5",
            "Self-Destruct",
            "Kamikaze attack",
            "(Orbit)",
            "(Release carried cargo)",
            "Deliver/drop off",
            "41",
            "(Attack)",
            "Load",
            "Sit and Fire",
            "Repair Self",
            "Defect",
            "Self capture",
            "*Make",
            "Becon",
            "Hyper to Region",
            "*Relaunch",
            "Transfer Cargo",
            "Inspect targets",
            "*Await Assembly",
            "*Await Disassembly",
            "*Construct Train",
            "Park at",
            "*Board to Defuse",
            "Start over",
            "*Take Apart Train",
            "Work on",
            "*Dock to Load",
            "Follow Targets",
            "Homing",
            "65",
            "66",
            "67",
            "68",
            "69",
            "70",
            "71",
            "72",
    };

    public static readonly string[] OrderSpeedBoxStrings = new string[]
    {
            "   0%",
            " 10%",
            " 20%",
            " 30%",
            " 40%",
            " 50%",
            " 60%",
            " 70%",
            " 80%",
            " 90%",
            "100%",
    };

    public static readonly string[] T1ClassStrings = new string[]
    {
            "Rebel",
            "Imperial",
            "Blue",
            "Yellow",
            "Red",
            "Azzameen",
    };

    public static readonly string[] T2ClassStrings = new string[]
    {
            "None",
            "Space Bombs",
            "Heavy Rockets",
            "Concussion Missiles",
            "Proton Torpedoes",
            "Advanced Missiles",
            "Advanced Torpedoes",
            "Mag Pulse Torpedoes",
            "(Ion Pulse Torpedoes)",
    };

    public static readonly string[] T3ClassStrings = new string[]
    {
            "None",
            "Chaff",
            "Flare",
            "(Cluster mine)",
    };

    public static readonly string[] T4ClassStrings = new string[]
    {
            "None",
            "Tractor",
            "Jamming",
            "Decoy",
            "(Energy Transfer)",
    };

    public static readonly string[] T2IndexStrings = new string[]
    {
            "0",
            "inspected",
            "finished docking?",
            "3",
            "disabled",
            "attacked",
            "shields at 0%?",
            "special craft",
            "non-special craft",
            "Players",
            "non-player",
            "11",
            "not disabled",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
    };

    public static readonly string[] T4IndexStrings = new string[]
    {
            "Stationary.        Systems: 100%         No return fire.",
            "Fly to Mothership if assigned, otherwise to hyperspace.  Disregards Targets.  Returns fire.",
            "Circle through enabled WPs specified # of times.   Disregards Targets.    Returns fire.",
            "Circle through enabled WPs specified # of times. Evades attackers. Returns fire. Disregard Targets.",
            "Fly to Rendezvous WP and await boarding.   Disregards Targets.  Returns fire.",
            "Stationary.       Systems at 0%         No Return fire.",
            "Stationary.       Systems at 0%         No Return fire.",
            "Attack Targets.        (Not for Capital ships. Use a Starship order)",
            "Attack ships with orders to escort the designated Targets.",
            "Attack craft once they have attacked designated Targets.   Ignores boarding craft. ",
            "Attack craft with orders to attack OR board designated Targets.",
            "Attack to disable Targets.     Use missiles to bring down shields.",
            "Board Targets (if stationary) to give the Targets its cargo.",
            "Board Targets (if stationary) to take their cargo.",
            "Board Target (if stationary) to exchange cargo with the Target.",
            "Board Target (if stationary) to capture it. Once captured, Target will Go Home.",
            "Board Target (if stationary) to destroy it. Target will explode when docking is complete.",
            "Board Target to pick it up and carry it for the rest of its mission.",
            "Drops off the designated FG   (NOT Targets)",
            "Wait for specified time, then continue to next order.   Systems: 100%    Returns fire.",
            "Wait for specified time, then continue to next order.   Systems: 100%    Returns fire.",
            "Circle through enabled WPs specified # of times.   Attacks Targets.   Returns fire.",
            "SShip await return of all FGs with it as their Mothership.   Attacks Targets.   Returns fire.",
            "SShip await launch of all FGs with it as their Mothership.   Attacks Targets.   Returns fire.",
            "Circle through enabled WPs and attack all FGs attacking Targets.  Returns fire.",
            "Circle through enabled WPs and attack all FGs attacking Targets.  Returns fire.",
            "Circle through enabled WPs and attack Targets.    Returns fire.",
            "Circle through enabled WPs and attack to disable Targets.  Returns fire (with lasers).",
            "Stationary.       Systems at 100%         No Return fire. ",
            "Fly to Mothership if assigned, otherwise to hyperspace.  Attacks Targets.  Returns fire.",
            "Stationary.       Systems at 100%         No Return fire.",
            "Board to ? - After boarding, Target continues its orders.",
            "Board Targets (if stationary) to repair it. Once repaired, Target continues its orders.",
            "Stationary.       Systems at 100%         No Return fire.",
            "Stationary.       Systems at 100%         No Return fire.",
            "Stationary.       Systems at 100%         No Return fire.",
            "Craft will explode after specified delay time.    No return fire.",
            "Collide with Target until it destroys itself, also fires lasers at Target.   Returns fire.",
            "",
            "",
            "",
            "",
            "",
            "Load Objects",
            "Stationary     Attack targets (with missiles if specified).",
            "Ship will repair itself in the specified time.",
            "Defect to specified IFF and Team",
            "Self Capture to specified IFF",
            "(Caution: Needs further testing)",
            "For Hyperbuoys",
            "Jump to specified Region. If set to wait, circles WPs specified times.",
            "(Caution: Needs further testing)",
            "Board to transfer",
            "Inspect specified targets",
            "(Caution: Needs further testing)",
            "(Caution: Needs further testing)",
            "(Caution: Needs further testing)",
            "Park at target for specified time. If inside, set WPs to closest dockpoint in hangar.",
            "(Caution: Needs further testing)",
            "",
            "(Caution: Needs further testing)",
            "Work On specified Component of Target",
            "(Caution: Needs further testing)",
            "Follow Targets",
            "Home in on target in specifed direction and number of loops.",
    };

    public static readonly string[] MsgColorBoxStrings = new string[]
    {
          "Green",
          "Red",
          "Blue",
          "Yellow",
          "Red",
          "Purple",
    };
}
