namespace AlliED.Impl.Enumerations;

internal enum BriefingCommandEnum : ushort
{
    None = 0,
    Seek = 1,
    ShipIndex = 2,
    PageBreak = 3,
    BriefingTitle = 4,
    BriefingText = 5,
    MoveMap = 6,
    ScaleMap = 7,
    ClearFlightGroupTags = 8,
    FlightGroupTags1 = 9,
    FlightGroupTags2 = 10,
    FlightGroupTags3 = 11,
    FlightGroupTags4 = 12,
    FlightGroupTags5 = 13,
    FlightGroupTags6 = 14,
    FlightGroupTags7 = 15,
    FlightGroupTags8 = 16,
    ClearTextTags = 17,
    TextTag1 = 18,
    TextTag2 = 19,
    TextTag3 = 20,
    TextTag4 = 21,
    TextTag5 = 22,
    TextTag6 = 23,
    TextTag7 = 24,
    TextTag8 = 25,
    NewIcon = 26,
    ShowShipData = 27,
    MoveIcon = 28,
    RotateIcon = 29,
    ChangeRegion = 30,
    ZoomParagraph = 31,
    Unused7 = 32,
    Unused8 = 33,
    BriefingEnd = 34,
    ClearIcon = 35,
    IconInfo = 36,
}
