namespace AlliED.Impl.Enumerations;

internal enum MeshTypeEnum : uint
{
    Default = 0,
    MainHull = 1,
    Wing = 2,
    Fuselage = 3,
    GunTurret = 4,
    SmallGun = 5,
    Engine = 6,
    Bridge = 7,
    ShieldGen = 8,
    EnergyGen = 9,
    Launcher = 10,
    CommSys = 11,
    BeamSys = 12,
    CommandSys = 13,
    DockingPlat = 14,
    LandingPlat = 15,
    Hangar = 16,
    CargoPod = 17,
    MiscHull = 18,
    Antenna = 19,
    RotaryWing = 20,
    RotaryGunTurret = 21,
    RotaryLauncher = 22,
    RotaryCommSys = 23,
    RotaryBeamSys = 24,
    RotaryCommandSys = 25,
    Hatch = 26,
    Custom = 27,
    WeaponSys1 = 28,
    WeaponSys2 = 29,
    PowerReg = 30,
    Reactor = 31,
}
